"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.scalaQuery = exports.elispQuery = exports.embeddedTemplateQuery = exports.zigQuery = exports.tlaPlusQuery = exports.systemrdlQuery = exports.tomlQuery = exports.ocamlQuery = exports.luaQuery = exports.htmlQuery = exports.elixirQuery = exports.cssQuery = exports.kotlinQuery = exports.swiftQuery = exports.goQuery = exports.csharpQuery = exports.cQuery = exports.cppQuery = exports.rubyQuery = exports.rustQuery = exports.javaQuery = exports.javascriptQuery = exports.pythonQuery = exports.tsxQuery = exports.typescriptQuery = exports.vueQuery = exports.phpQuery = exports.solidityQuery = void 0;
var solidity_1 = require("./solidity");
Object.defineProperty(exports, "solidityQuery", { enumerable: true, get: function () { return solidity_1.solidityQuery; } });
var php_1 = require("./php");
Object.defineProperty(exports, "phpQuery", { enumerable: true, get: function () { return __importDefault(php_1).default; } });
var vue_1 = require("./vue");
Object.defineProperty(exports, "vueQuery", { enumerable: true, get: function () { return vue_1.vueQuery; } });
var typescript_1 = require("./typescript");
Object.defineProperty(exports, "typescriptQuery", { enumerable: true, get: function () { return __importDefault(typescript_1).default; } });
var tsx_1 = require("./tsx");
Object.defineProperty(exports, "tsxQuery", { enumerable: true, get: function () { return __importDefault(tsx_1).default; } });
var python_1 = require("./python");
Object.defineProperty(exports, "pythonQuery", { enumerable: true, get: function () { return __importDefault(python_1).default; } });
var javascript_1 = require("./javascript");
Object.defineProperty(exports, "javascriptQuery", { enumerable: true, get: function () { return __importDefault(javascript_1).default; } });
var java_1 = require("./java");
Object.defineProperty(exports, "javaQuery", { enumerable: true, get: function () { return __importDefault(java_1).default; } });
var rust_1 = require("./rust");
Object.defineProperty(exports, "rustQuery", { enumerable: true, get: function () { return __importDefault(rust_1).default; } });
var ruby_1 = require("./ruby");
Object.defineProperty(exports, "rubyQuery", { enumerable: true, get: function () { return __importDefault(ruby_1).default; } });
var cpp_1 = require("./cpp");
Object.defineProperty(exports, "cppQuery", { enumerable: true, get: function () { return __importDefault(cpp_1).default; } });
var c_1 = require("./c");
Object.defineProperty(exports, "cQuery", { enumerable: true, get: function () { return __importDefault(c_1).default; } });
var c_sharp_1 = require("./c-sharp");
Object.defineProperty(exports, "csharpQuery", { enumerable: true, get: function () { return __importDefault(c_sharp_1).default; } });
var go_1 = require("./go");
Object.defineProperty(exports, "goQuery", { enumerable: true, get: function () { return __importDefault(go_1).default; } });
var swift_1 = require("./swift");
Object.defineProperty(exports, "swiftQuery", { enumerable: true, get: function () { return __importDefault(swift_1).default; } });
var kotlin_1 = require("./kotlin");
Object.defineProperty(exports, "kotlinQuery", { enumerable: true, get: function () { return __importDefault(kotlin_1).default; } });
var css_1 = require("./css");
Object.defineProperty(exports, "cssQuery", { enumerable: true, get: function () { return __importDefault(css_1).default; } });
var elixir_1 = require("./elixir");
Object.defineProperty(exports, "elixirQuery", { enumerable: true, get: function () { return __importDefault(elixir_1).default; } });
var html_1 = require("./html");
Object.defineProperty(exports, "htmlQuery", { enumerable: true, get: function () { return __importDefault(html_1).default; } });
var lua_1 = require("./lua");
Object.defineProperty(exports, "luaQuery", { enumerable: true, get: function () { return __importDefault(lua_1).default; } });
var ocaml_1 = require("./ocaml");
Object.defineProperty(exports, "ocamlQuery", { enumerable: true, get: function () { return ocaml_1.ocamlQuery; } });
var toml_1 = require("./toml");
Object.defineProperty(exports, "tomlQuery", { enumerable: true, get: function () { return toml_1.tomlQuery; } });
var systemrdl_1 = require("./systemrdl");
Object.defineProperty(exports, "systemrdlQuery", { enumerable: true, get: function () { return __importDefault(systemrdl_1).default; } });
var tlaplus_1 = require("./tlaplus");
Object.defineProperty(exports, "tlaPlusQuery", { enumerable: true, get: function () { return __importDefault(tlaplus_1).default; } });
var zig_1 = require("./zig");
Object.defineProperty(exports, "zigQuery", { enumerable: true, get: function () { return zig_1.zigQuery; } });
var embedded_template_1 = require("./embedded_template");
Object.defineProperty(exports, "embeddedTemplateQuery", { enumerable: true, get: function () { return __importDefault(embedded_template_1).default; } });
var elisp_1 = require("./elisp");
Object.defineProperty(exports, "elispQuery", { enumerable: true, get: function () { return elisp_1.elispQuery; } });
var scala_1 = require("./scala");
Object.defineProperty(exports, "scalaQuery", { enumerable: true, get: function () { return scala_1.scalaQuery; } });
//# sourceMappingURL=index.js.map